name: '问题反馈'
labels:
  - bug
description: 'BUG、不兼容、崩溃等'
body:
  - type: dropdown
    id: modloader
    attributes:
      label: 'Mod 加载器'
      options:
        - Forge
        - Fabric
        - Quilt
    validations:
      required: true
  - type: input
    id: modloader-version
    attributes:
      label: 'Mod 加载器版本'
      placeholder: "如: 0.14.22 + 0.89.3+1.20.2"
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: 'Minecraft 版本'
      placeholder: "如: 1.20.2"
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: '本模组版本'
      placeholder: "如: 1.0.0"
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: '整合包'
      description: |
        '如果是整合包，请填写整合包信息。'
  - type: input
    attributes:
      label: 'latest.log'
      description: |
        '请发文件或链接，请勿粘贴内容。'
        '可使用如下链接粘贴：'
        'https://gist.github.com/'
        'https://paste.gg/'
    validations:
      required: true
  - type: textarea
    attributes:
      label: '详细描述'